from django.urls import path
from . import views
from .views import BusinessRegistrationView

urlpatterns = [
    path('', views.home, name="home"),
    path('shop/', views.shop, name="shop"),
    path('products/', views.products, name="products"),
    path('services/', views.services, name="services"),
    path('search/', views.search, name='search'),
    path('community/', views.community, name="community"),
    path('community/?country=<int:country_id>', views.community, name='community'),
    path('events/', views.events, name='events'),
    path('create-event/', views.create_event, name='create_event'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event/<int:event_id>/edit/', views.edit_event, name='edit_event'),
    path('user/register-business', BusinessRegistrationView.as_view(), name="business_registration"),
    path('business/<slug:business_slug>/', views.BusinessDetailView.as_view(), name='business_detail'),
    path('quick-shop/<slug:product_slug>/', views.quick_shop_view, name='quick_shop'),
    path('business/<slug:business_slug>/edit/', views.edit_business, name='edit_business'),
    path('business/<slug:business_slug>/product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('business/<slug:business_slug>/product/<slug:product_slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('ajax/product/<slug:business_slug>/<slug:product_slug>/', views.AjaxProductDetailView.as_view(), name='ajax_product_detail'),
    path('business/<slug:business_slug>/product/<slug:product_slug>/edit/', views.ProductEditView.as_view(), name='product_edit'),
    path('business/<slug:business_slug>/service/create/', views.ServiceCreateView.as_view(), name='service_create'),
    path('business/<slug:business_slug>/service/<slug:service_slug>/edit/', views.ServiceEditView.as_view(), name='service_edit'),
    path('business/<slug:business_slug>/service/<slug:service_slug>/', views.service_detail, name='service_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/update_quantity/', views.CartView.as_view(), name='update_quantity'),
    path('cart/data/', views.CartView.as_view(), name='cart_data'),
    path('cart/add/', views.CartView.as_view(), name='add'),
    path('checkout/', views.checkout, name="checkout"),
    path('message/<slug:business_slug>/', views.message_seller, name='message_seller'),
    path('messages/', views.user_messages_view, name='user_messages'),
    path('messages/<slug:business_slug>/', views.user_messages_view, name='user_messages_with_slug'),
]