# Generated by Django 5.0.4 on 2024-05-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='slug',
            new_name='business_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='slug',
            new_name='service_slug',
        ),
    ]
