# Generated by Django 5.0.4 on 2024-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
