# Generated by Django 5.0.4 on 2024-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_delivery_time',
            field=models.PositiveIntegerField(help_text='Maximum estimated delivery time in business days', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_delivery_time',
            field=models.PositiveIntegerField(help_text='Minimum estimated delivery time in business days', null=True),
        ),
    ]
