# Generated by Django 4.2.13 on 2024-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_business_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
        migrations.RemoveField(
            model_name='business',
            name='state',
        ),
        migrations.AddField(
            model_name='business',
            name='countries',
            field=models.ManyToManyField(to='business.country'),
        ),
        migrations.AddField(
            model_name='business',
            name='states',
            field=models.ManyToManyField(to='business.state'),
        ),
    ]
