# Generated by Django 4.2.13 on 2024-05-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
