# Generated by Django 4.2.13 on 2024-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
