# Generated by Django 4.2.13 on 2024-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_variations/'),
        ),
    ]
