# Generated by Django 4.2.13 on 2024-05-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_productvariation_color_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=False),
        ),
    ]
