# Generated by Django 4.2.13 on 2024-05-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_product_has_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
