# Generated by Django 4.2.13 on 2024-05-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_alter_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('color__isnull', False), ('size__isnull', True)), models.Q(('color__isnull', True), ('size__isnull', False)), _connector='OR'), name='business_productvariation_color_or_size'),
        ),
    ]
