# Generated by Django 4.2.13 on 2024-05-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_productvariation_business_productvariation_color_or_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('size', 'Size'), ('color', 'Color')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productvariation',
            name='business_productvariation_color_or_size',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='color_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='business.product'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='business.variation'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('variation', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'name')},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='size',
        ),
    ]
