# Generated by Django 4.2.13 on 2024-05-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_variation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set(),
        ),
    ]
