# Generated by Django 4.2.13 on 2024-05-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_cart_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variation',
        ),
        migrations.CreateModel(
            name='CartItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='business.cart')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.productvariation')),
            ],
        ),
    ]
