# Generated by Django 4.2.13 on 2024-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_remove_cart_variation_cartitemvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
