# Generated by Django 4.2.13 on 2024-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
