# Generated by Django 4.2.13 on 2024-06-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_rename_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
