# Generated by Django 4.2.13 on 2024-06-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
