# Generated by Django 4.2.13 on 2024-06-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_order_ref_code_order_refund_granted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
