# Generated by Django 4.2.13 on 2024-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_alter_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='ordered', max_length=20),
        ),
    ]
