# Generated by Django 4.2.13 on 2024-06-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_product_new_releases_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing, Shoes & Jewelry'), ('BK', 'Books'), ('HM', 'Home & Kitchen'), ('BE', 'Beauty & Personal Care'), ('TY', 'Toys & Games'), ('SP', 'Sports & Outdoors'), ('AU', 'Automotive'), ('HE', 'Health & Household'), ('GR', 'Grocery & Gourmet Food'), ('PT', 'Pet Supplies'), ('OF', 'Office Products'), ('TL', 'Tools & Home Improvement'), ('MV', 'Movies & TV'), ('GD', 'Garden & Outdoor'), ('HN', 'Handmade'), ('BA', 'Baby'), ('IN', 'Industrial & Scientific'), ('AR', 'Arts, Crafts & Sewing'), ('MU', 'Musical Instruments'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
