# Generated by Django 4.2.13 on 2024-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
