# Generated by Django 4.2.13 on 2024-08-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0042_country_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='banner_image',
            field=models.ImageField(default='business_profiles/1.jpg', upload_to='business_banners/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(default='name@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='profile_picture',
            field=models.ImageField(default='business_profiles/1.jpg', upload_to='business_profiles/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(default='www.website.com'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='1.jpg', null=True, upload_to='services/'),
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='services/videos/')),
                ('service', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='business.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='1.jpg', upload_to='services/additional_images/')),
                ('service', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='business.service')),
            ],
        ),
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='business.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
