# Generated by Django 4.2.13 on 2024-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_alter_business_banner_image_alter_business_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
