# Generated by Django 4.2.13 on 2024-08-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='service',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='video', to='business.service'),
        ),
    ]
