# Generated by Django 4.2.13 on 2024-08-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_alter_servicevideo_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='business.service'),
        ),
    ]
