# Generated by Django 4.2.13 on 2024-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_alter_servicevideo_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/additional_images/'),
        ),
    ]
